### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username, password) in order to use features in the game that are exclusively available to registered users. 

### ISSUE THREAD

**Issue by nmamie** [sopra-fs23-group-27/sopra-fs23-group-27-server#1]
**Acceptance Criteria:**

- [x] Upon successful user registration, the overview dashboard of the UI is shown, and the user is automatically logged in.
- [x] Upon failure, an error is displayed, and the user is redirected (back) to the register screen. A register error can be that a username is already taken.
- [x] The creation date of a user and a user ID are saved to the internal database record.  
- [x] Logged-in users can log out and log back into their registered profile. 

**Development Tasks:**

- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#49
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#1
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#2
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#3
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#4
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#114 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#135 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#158 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#124
