### ISSUE TITLE
As a player, during each round, I want to be able to see the other players' guesses in order to have an additional layer of interactivity and to profit from the other players' associations.

### ISSUE THREAD

**Issue by e-schuh** [sopra-fs23-group-27/sopra-fs23-group-27-server#11]
**Acceptance Criteria:**

- [x] #52
- [x] The player is able to see the username of the opponent, who typed the guess.
- [x] Only the last 15-30 guesses are displayed.
- [x] Players that already correctly guessed the country cannot make any further guesses for the current round.
- [x] Guesses are displayed in a chat-like window that is constantly updated. 

**Development Tasks:**

- [x] #19 
- [x] #20 
- [x] #21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#56
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#71
