### ISSUE TITLE
As a game creator, I want to be able to adjust the game settings of a game in ADVANCED mode in order to customize the game experience.

### ISSUE THREAD

**Issue by rspecker** [sopra-fs23-group-27/sopra-fs23-group-27-server#15]
**Acceptance Criteria:**

- [x] The game creator can set the number of seconds until the first hint is shown to an integer between 0 and 15.
- [x] The game creator can set the hints interval to an integer between 3 and 10.
- [x] The game creator can set the time limit in seconds to an integer between 20 sec-onds and 120 seconds.
- [x] There is a default set of settings that is taken, if the game creator does not want to adjust the game.

**Development Tasks:**
- [x] #19 
- [x] #20 
- [x] #21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#41 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#67 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#46
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#82
- [x] #98 
- [x] #100 
- [x] #131
