### ISSUE TITLE
As a player in the advanced mode, I want to be able to see multiple hints for the country in order to help my memory to correctly guess the country.

### ISSUE THREAD

**Issue by e-schuh** [sopra-fs23-group-27/sopra-fs23-group-27-server#16]
**Acceptance Criteria:**

- [x] The hints must be relevant to the country. 
- [x] Wrong facts may not be displayed (e.g., "for France, the capital is Rome" cannot be displayed).
- [x] The hints must be displayed at fixed intervals chosen by the game creator such that the players have enough time to think and reason about their guesses.
- [x] The hints must be different each time the user plays the game to keep the game interesting and challenging (e.g., life expectancy for females in one round and population density in another round).

**Development Tasks:**
- [x] #19 
- [x] #20 
- [x] #21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#44
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#32
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#73
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#74
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#92
- [x] #101 
- [x] #102
