### ISSUE TITLE
As a player, after each round of guessing, I want to see a scoreboard in order to see how I compare against the others.

### ISSUE THREAD

**Issue by e-schuh** [sopra-fs23-group-27/sopra-fs23-group-27-server#17]
**Acceptance Criteria:**

- [x] The scoreboard must be displayed at the end of each round.
- [x] The scoreboard should only display scores from players who have participated in the game.
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#54
- [x] The scoreboard must display the total score of each player for the current game (leaderboard). That is the summation of the points earned overall finished rounds of the current game.

**Development Tasks:**
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#45
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#32
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#77
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#103
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#98
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#66
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#123
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#125
