### ISSUE TITLE
As a user who chooses to create an account for the game (i.e., a registered and logged-in user), I want to be able to access an overview page that displays certain statistical metrics, i.e. overall number of distinct country flags correctly guessed or average answer speed of all my games played so far in order to assess my past performances playing the game. (This user story requires implementation of S1.)

### ISSUE THREAD

**Issue by rspecker** [sopra-fs23-group-27/sopra-fs23-group-27-server#18]
**Acceptance Criteria:**

- [x] Only for users that chose to register, a separate performance metrics page is visible.
- [x] Displayed metrics are number of countries that were correctly guessed, average time to choose an answer and number of games played. 
- [x] For each metric, a short description is displayed.

**Development Tasks:**
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#96
- [x] #122
