### ISSUE TITLE
As a user, I want to create a private game session in order to compete with my friends.

### ISSUE THREAD

**Issue by rspecker** [sopra-fs23-group-27/sopra-fs23-group-27-server#3]
**Acceptance Criteria:**

- [x] By clicking on the button “START GAME” in the overview dashboard, a private game session with a unique ID and a QR code is created.
- [x] By creating a private game, the user gets the role GAME CREATOR assessed.
- [x] The user must define the game session mode either as BASIC or ADVANCED.
- [x] Other users can join the game by scanning the QR code displayed.
- [x] Alternatively, other users can also join the game by typing in the unique URL. 

**Development Tasks:**

- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] #59 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#41
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#46
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#7
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#8
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#48
- [x] #127 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#124
