### ISSUE TITLE
As a player, I want to guess countries based on random images of the respective country shown on the screen in order to test my world knowledge, beat my friends and win the game.

### ISSUE THREAD

**Issue by e-schuh** [sopra-fs23-group-27/sopra-fs23-group-27-server#4]
**Acceptance Criteria:**

- [ ] For every country to be guessed by the players, a random image of the country is simultaneously displayed to all players on their respective screens.
- [ ] Once a country is correctly guessed by at least one of the players, the round is finished, and a new round is started (until the specified number of rounds of the game are played)
- [ ] Should the players be unable to guess the country based on the image and the hints provided, a new image is automatically shown after a certain amount of time.
- [ ] For every round in a game, a new country is chosen; i.e., in one game, all countries to be guessed are distinct.

**Development Tasks:**
 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#56 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#9
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#10
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#75
