### ISSUE TITLE
As a user, I want to create a public game session in order to compete with other people around the world.

### ISSUE THREAD

**Issue by rspecker** [sopra-fs23-group-27/sopra-fs23-group-27-server#5]
**Acceptance Criteria:**

- [x] By clicking on the button “START PUBLIC GAME” in the overview dashboard, a public game session with a unique name is created.
- [x] By creating a public game, the user gets the role GAME CREATOR assigned.
- [x] The user must define the game session mode either as BASIC or ADVANCED.
- [x] Any other user can join the game via the overview dashboard by selecting the game with the corresponding name.

**Development Tasks:**

- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#40
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#41
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#46
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#33
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#11
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#12
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#13
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#48
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#44
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#57
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#72
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#98
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#124
