### ISSUE TITLE
As a player, I want to guess countries based on their flags shown on the screen in order to test my world knowledge, beat my friends and win the game.

### ISSUE THREAD

**Issue by e-schuh** [sopra-fs23-group-27/sopra-fs23-group-27-server#6]
**Acceptance Criteria:**

- [x] For every country to be guessed by the players, the flag of the country is simultaneously displayed to all players on their respective screens.
- [x] Once a country is correctly guessed by at least one of the players, the round is finished, and a new round is started (until the specified number of rounds of the game are played).
- [x] For every round in a game, a new country is chosen; i.e., in one game, all countries to be guessed are distinct.

**Development Tasks:**

- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#56
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#14
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#84
- [x] #91 
- [x] #98 
- [x] #112  
- [x] #113 
- [x] #128
