### ISSUE TITLE
As a user, I want to be able to join a private game in order to compete with my friends.

### ISSUE THREAD

**Issue by rspecker** [sopra-fs23-group-27/sopra-fs23-group-27-server#7]
**Acceptance Criteria:**

- [x] By clicking on the button “JOIN GAME” at the dashboard overview, the user can join the private game session by typing in the game id, generated by the game crea-tor.
- [x] If the entered URL does not exist, or the game already is finished, an error is prompt-ed and the user is redirected to the overview page.
- [x] By scanning the QR code created by the game creator, the user can join the private game session.
- [x] If the game attached to the QR code is already finished, an error is prompted and the user is redirected to the overview page.

**Development Tasks:**

- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#41
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#42
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#15
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#16
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#32
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#48
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#97
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#124
