### ISSUE TITLE
As a user, I want to be able to join a public game in order to compete with my friends.

### ISSUE THREAD

**Issue by rspecker** [sopra-fs23-group-27/sopra-fs23-group-27-server#8]
**Acceptance Criteria:**

- [x] A list of all currently active games is displayed in the dashboard overview
- [x] Every active game is listed with its unique name and the number of participating players is displayed.
- [x] By clicking on a specific active game, the user can join this game.

**Development Tasks:**

- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#19 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#20 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#21 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#39 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#47
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#41
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#43 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#33
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#15
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#16
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#32
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#48
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#57 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#60
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#63
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#85 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-server#86 
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#56
- [x] #90 
- [x] #109 
- [x] #115 
- [x] #124 
- [x] #133 
- [x] #148
- [x] sopra-fs23-group-27/sopra-fs23-group-27-client#124
